version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm run prod

artifacts:
  files:
    - '**/*'